name = input("โปรดกรอกชื่อ\n")
nickname = input("โปรดกรอกชื่อเล่น\n")
height = float(input("โปรดกรอกส่วนสูง\n"))
weight = float(input("โปรดกรอกน้ำหนัก\n"))
age = input("โปรดกรอกอายุ\n")
stuid = input("โปรดกรอกรหัสประจำตัวนักศึกษา\n")
years = input("โปรดกรอกชั้นปี\n")
hw = height + weight
print("ชื่อ:" + name + "อายุ:" + age)
print("รหัสประจำตัวนักศึกษา:" + stuid + "ชั้นปี:" + years)
print("ชื่อเล่น:" + nickname)
print("ส่วนสูง:" + str(height),"เซนติเมตร" + "น้ำหนัก:" + str(weight)+"กิโลกรัม")
print("ส่วนสูง + น้ำหนัก" + str(hw))